"""`cartographer graph` -- the command that generates README's own
architecture diagram (regenerated by hand from real output each time the
import structure drifts, most recently 2026-09-10 when it still showed a
deleted module). Had zero test coverage despite that; a silent regression
here would only be caught by eyeballing a diagram, which is exactly how the
prior drift went unnoticed for a session.

All real: build_graph and render.py are fast, pure, and need no Docker or
model, so unlike `cartographer score` (test_score_cli.py) this doesn't mock
anything.
"""

from __future__ import annotations

import textwrap

from typer.testing import CliRunner

from cartographer.cli import app

runner = CliRunner()


def write(root, files: dict[str, str]):
    for rel, src in files.items():
        p = root / rel
        p.parent.mkdir(parents=True, exist_ok=True)
        p.write_text(textwrap.dedent(src).strip() + "\n", encoding="utf-8")
    return root


def repo(tmp_path):
    # `import pkg.b` (absolute, dotted) rather than `from pkg import b`: the
    # latter is genuinely ambiguous in real Python (b could be a submodule or
    # an attribute of pkg/__init__.py) and the analyzer resolves it to the
    # package's __init__ rather than pkg/b.py -- a real, separate finding
    # about import resolution, not something this CLI test should chase.
    return write(
        tmp_path,
        {
            "pkg/__init__.py": "",
            "pkg/a.py": "import pkg.b\n",
            "pkg/b.py": "import pkg.c\n",
            "pkg/c.py": "x = 1\n",
        },
    )


def test_graph_default_format_is_mermaid(tmp_path):
    res = runner.invoke(app, ["graph", "--repo", str(repo(tmp_path))])
    assert res.exit_code == 0, res.output
    assert "graph LR" in res.output
    # Labels are bare module names within their directory subgraph (matches
    # the README's own self-generated diagram), not full paths.
    assert '["a"]' in res.output and '["c"]' in res.output


def test_graph_dot_format(tmp_path):
    res = runner.invoke(app, ["graph", "--repo", str(repo(tmp_path)), "--format", "dot"])
    assert res.exit_code == 0, res.output
    assert "digraph" in res.output


def test_graph_summary_format_ranks_by_fan_in(tmp_path):
    res = runner.invoke(app, ["graph", "--repo", str(repo(tmp_path)), "--format", "summary"])
    assert res.exit_code == 0, res.output
    assert "fan-in" in res.output
    assert "pkg/c" in res.output


def test_graph_exclude_drops_matching_modules(tmp_path):
    # _excluded() matches whole path segments or the file stem ("c", not
    # "pkg/c" -- render.py's own docstring warns a substring match once
    # silently dropped an unrelated package via "eval" matching "retrieval").
    included = runner.invoke(app, ["graph", "--repo", str(repo(tmp_path))])
    excluded = runner.invoke(app, ["graph", "--repo", str(repo(tmp_path)), "--exclude", "c"])
    assert '["c"]' in included.output
    assert '["c"]' not in excluded.output


def test_graph_writes_to_a_file_instead_of_stdout(tmp_path):
    out_file = tmp_path / "diagram.mmd"
    res = runner.invoke(
        app, ["graph", "--repo", str(repo(tmp_path)), "--out", str(out_file)]
    )
    assert res.exit_code == 0, res.output
    assert out_file.exists()
    assert "graph LR" in out_file.read_text(encoding="utf-8")
    assert "graph LR" not in res.output, "must not also print to stdout when --out is given"


def test_graph_refuses_rather_than_silently_truncates(tmp_path):
    """max_nodes is a refusal, not a slice (render.py's own docstring) --
    confirms the CLI actually surfaces that refusal as a clean error, not an
    uncaught traceback."""
    res = runner.invoke(
        app, ["graph", "--repo", str(repo(tmp_path)), "--max-nodes", "0"]
    )
    assert res.exit_code == 2
    assert "max_nodes" in res.output
